Name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        # Folder ထဲဝင်ပြီးမှ Build လုပ်ဖို့ ပြင်ဆင်ထားပါတယ်
        run: |
          cd V2rayNG
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: v2rayNG-debug
          # Path ကိုလည်း folder အသစ်အတိုင်း ပြင်ပေးရပါတယ်
          path: V2rayNG/app/build/outputs/apk/fdroid/debug/*.apk
