name: Super Easy Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Auto-Find and Build
        run: |
          # gradlew ရှိတဲ့ နေရာကို ရှာမယ်
          find . -name "gradlew" -exec chmod +x {} \;
          GRADLEW_EXEC=$(find . -name "gradlew" | head -n 1)
          
          # အဲဒီ folder ထဲဝင်ပြီး Build လုပ်မယ်
          cd $(dirname $GRADLEW_EXEC)
          ./gradlew assembleDebug --no-daemon

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: My-v2rayNG-App
          path: "**/build/outputs/apk/**/*.apk"
