name: Build My Custom APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          # gradlew ဖိုင် ဘယ်မှာရှိလဲ ရှာပြီး အဲဒီ folder ထဲဝင်မယ်
          GRADLEW_PATH=$(find . -name gradlew)
          GRADLE_DIR=$(dirname $GRADLEW_PATH)
          cd $GRADLE_DIR
          
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: My-v2rayNG-APK
          # APK ဖိုင်ကို တစ်စုံလုံး လိုက်ရှာပြီး တင်ပေးမှာပါ
          path: "**/build/outputs/apk/**/*.apk"
